# Generated by Django 5.2.8 on 2025-12-01 12:26

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to=core.models.product_image_upload_to, verbose_name='Изображение'),
        ),
    ]
