# Generated by Django 5.2.8 on 2025-11-28 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(default='+7 (XXX) XXX-XX-XX', max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(default='info@palleteshop.ru', max_length=254, verbose_name='Email')),
                ('address', models.CharField(default='Москва, ул. Примерная, 123', max_length=255, verbose_name='Адрес')),
                ('address_link', models.URLField(blank=True, help_text='Ссылка на Google Maps или Яндекс.Карты', null=True, verbose_name='Ссылка на карту')),
            ],
            options={
                'verbose_name': 'Настройки сайта',
                'verbose_name_plural': 'Настройки сайта',
            },
        ),
    ]
