# Generated by Django 5.2.8 on 2025-11-28 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='working_hours_saturday',
            field=models.CharField(default='10:00 - 16:00', max_length=50, verbose_name='Режим работы (Суббота)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='working_hours_sunday',
            field=models.CharField(default='Выходной', max_length=50, verbose_name='Режим работы (Воскресенье)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='working_hours_weekdays',
            field=models.CharField(default='9:00 - 18:00', max_length=50, verbose_name='Режим работы (Пн-Пт)'),
        ),
    ]
