# Generated by Django 5.2.8 on 2025-11-29 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_sitesettings_working_hours_saturday_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='avito_link',
            field=models.URLField(blank=True, help_text='Полная ссылка на профиль на Avito', null=True, verbose_name='Ссылка на Avito'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='telegram_link',
            field=models.URLField(blank=True, help_text='Полная ссылка на Telegram (например, t.me/username)', null=True, verbose_name='Ссылка на Telegram'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='vk_link',
            field=models.URLField(blank=True, help_text='Полная ссылка на страницу ВКонтакте', null=True, verbose_name='Ссылка на VK'),
        ),
    ]
