# Generated by Django 5.2.8 on 2025-12-03 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_sitesettings_avito_link_sitesettings_telegram_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='whatsapp_link',
            field=models.URLField(blank=True, help_text='Полная ссылка на WhatsApp (например, https://wa.me/79991234567)', null=True, verbose_name='Ссылка на WhatsApp'),
        ),
    ]
